#!/usr/bin/env bash
set -euo pipefail

# Render secrets-backend host paths into an env file for docker compose.
#
# This avoids hard-coding /mnt/appdata on dev machines while keeping a stable
# layout on the deploy host.
#
# Output:
#   ./.env.connect (gitignored by default in most setups)

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

SERVER_DATA_ROOT="${SERVER_DATA_ROOT:-"$(./scripts/server_data_root.sh)"}"
BW_DIR="${SERVER_DATA_ROOT}/server/secrets/bitwarden-sm"

cat > .env.connect <<EOF
# Generated by scripts/render_connect_env.sh
SERVER_DATA_ROOT=${SERVER_DATA_ROOT}
BWS_ENV_FILE=${BW_DIR}/bws.env
EOF

echo "Wrote .env.connect"
echo "SERVER_DATA_ROOT=${SERVER_DATA_ROOT}"
echo "Bitwarden SM artifacts dir: ${BW_DIR}"

