#!/usr/bin/env bash
set -euo pipefail

_SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "$_SCRIPTS_DIR/cache_env.sh"

if [[ "${1:-}" == "--print" ]]; then
  cat <<EOF
SERVER_ROOT=$SERVER_ROOT
CACHE_ROOT=$CACHE_ROOT
UV_CACHE_DIR=$UV_CACHE_DIR
NPM_CONFIG_CACHE=$NPM_CONFIG_CACHE
XDG_CACHE_HOME=$XDG_CACHE_HOME
RUFF_CACHE_DIR=$RUFF_CACHE_DIR
MYPY_CACHE_ROOT=$MYPY_CACHE_ROOT
PYTEST_CACHE_ROOT=$PYTEST_CACHE_ROOT
TOOL_ENV_ROOT=$TOOL_ENV_ROOT
HF_HOME=$HF_HOME
MODEL_CACHE_DIR=$MODEL_CACHE_DIR
TRANSFORMERS_CACHE=$TRANSFORMERS_CACHE
WHISPER_CACHE_DIR=$WHISPER_CACHE_DIR
EOF
  exit 0
fi

if [[ "${BASH_SOURCE[0]}" == "$0" ]] && [[ $# -gt 0 ]]; then
  exec "$@"
fi
